name: flux
description: "Flux - A modern Flutter application with Clean Architecture."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Database (Offline-first)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Navigation
  go_router: ^14.8.1

  # API
  http: ^1.2.0

  # Environment
  flutter_dotenv: ^5.2.1

  # Serialization & Code Generation Annotations
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Utilities
  path_provider: ^2.1.5
  intl: ^0.20.2

  # Charts
  fl_chart: ^0.70.2

  # Image & Utilities
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^20.1.0
  quick_actions: ^1.1.0
  workmanager: ^0.9.0+3
  confetti: ^0.8.0
  local_auth: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.4.7
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/images/logo.jpg"
